config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "search_item", to: "items#search"
  get "my_items", to: "items#my_items"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :destroy] do
    resource :friendships, only: [:create, :destroy, :show]
    member do
      get :follows, :followers, :favorites, :items, :like
    end
  end
  resources :coordinates

  get "search_friend", to: "users#search"
  post "save", to: "items#save"
  resources :items do
    collection do
      get "search"
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :coordinates

  has_many :likes, dependent: :destroy
  has_many :likes_items, through: :likes, source: :item

  has_many :active_relationships, class_name:
      "Friendship", foreign_key:
               :following_id, dependent:
               :destroy

  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name:
      "Friendship", foreign_key:
               :follower_id, dependent:
               :destroy
  has_many :followers, through: :passive_relationships, source: :following
  mount_uploader :avatar, ImageUploader


  validates :name, presence: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_save { self.email = email.downcase }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            format: {
                with: VALID_EMAIL_REGEX
            }
  validates :password,
            presence: true,
            length: { minimum: 8 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.search(param)
    param.strip!
    to_send_back = (name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.name_matches(param)
    matches("name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_follows_with?(user)
    !self.followings.where(id: user).exists?
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def update_with_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /coordinates/confirmation/new
  # def new
  #   super
  # end

  # POST /coordinates/confirmation
  # def create
  #   super
  # end

  # GET /coordinates/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, coordinates)
  #   super(resource_name, coordinates)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /coordinates/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /coordinates/password/new
  # def new
  #   super
  # end

  # POST /coordinates/password
  # def create
  #   super
  # end

  # GET /coordinates/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /coordinates/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, if: devise_controller?, only: [:update]
  # before_action :configure_sign_up_params, only: [:update]
  before_action :configure_account_update_params, if: :devise_controller?
  before_action :configure_account_update_params, only: [:update]

  # GET /coordinates/sign_up
  # def new
  #   super
  # end

  # POST /coordinates
  # def create
  #   super
  # end

  # GET /coordinates/edit
  # def edit
  #   super
  # end

  # PUT /coordinates
  def update
    super
  end

  # DELETE /coordinates
  # def destroy
  #   super
  # end

  # GET /coordinates/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, :introduction])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :introduction])
    end

  # The path used after sign up.
  # def after_sign_up_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(coordinates)
  #   super(coordinates)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, if: :devise_controller?




  # GET /coordinates/sign_in
  # def new
  #   super
  # end

  # POST /coordinates/sign_in
  # def create
  #   super
  # end

  # DELETE /coordinates/sign_out
  # def destroy
  #   super
  # end

  protected
    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /coordinates/unlock/new
  # def new
  #   super
  # end

  # POST /coordinates/unlock
  # def create
  #   super
  # end

  # GET /coordinates/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after unlocking the coordinates
  # def after_unlock_path_for(coordinates)
  #   super(coordinates)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :destroy, :follows, :followers]
  before_action :admin_user, only: [:index, :destroy]
  before_action :set_user, only: [:show, :destroy, :followers, :follows]


  def index
    @users = User.order(admin: :DESC, id: :ASC).page(params[:page]).per(5 * 2)
  end


  def show
    @items = @user.items.all.page(params[:page]).per(5)
    @likes = @user.likes.all.page(params[:page]).per(5)
    @coordinates = @user.coordinates.all.page(params[:page]).per(5)
    @friendship = Friendship.new
    @users = @user.followings
  end

  def like
    @user = current_user
    @likes = @user.likes.all.page(params[:page]).per(5)
  end



  def search
    if params[:user].present?
      @users = User.search(params[:user])
      @users = current_user.except_current_user(@users)
      if @users
        respond_to do |format|
          format.js { render partial: "users/partial/friend_result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: "users/partial/friend_result" }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: "users/partial/friend_result" }
      end
    end
  end

  def favorite
    @favorite_items = @user.favorites_items
  end

  def follows
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end



  def destroy
    @user.destroy
    flash[:success] = "ユーザー「#{@user.name}」は正常に削除されました"
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followers.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name' %>
        <%= link_to 'Stop Follow', user_friendships_path(user_id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-unfollow'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_follows.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name' %>
        <%= link_to 'Stop Follow', user_friendships_path(user_id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-unfollow'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/follows.html.erb
<div class="search-area search">
  <h1 class="text-center mt-4 friend-font">Friends</h1>
  <%= form_with url: search_friend_path, remote: true, method: :get do |f| %>
    <div class="form-group row friend-search">
      <div class="col-xs-9">
        <%= f.text_field :user, placeholder: "名前、メールアドレス", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-xs-3  search-btn">
        <%= button_tag type: :submit, class: "btn btn-primary btn-search" do %>
          <%= icon('fas', 'search') %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">
  <% if @users.present? %>
    <%= render 'users/partial/list' %>
  <% end %>
</div>

app/views/users/home.html.erb
<h1>Users#home</h1>
<p>Find me in app/views/users/home.html.erb</p>

app/views/users/index.html.erb
<% provide :title, 'すべてのユーザー' %>

<% if @users.any? %>

  <div class="container">
    <h1 class="text-center mt-4 mb-3 user-font">All User</h1>
    <div class="row user-cards">
      <% @users.each do |user| %>
        <div class="col-lg-4 col-md-6 col-sm-6 card-index">
          <div class="user-card card align-items-center">
            <% if user.avatar? %>
              <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
            <% else %>
              <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
            <% end %>
            <%= link_to user.name, user, class: 'user-name' %>

            <% if current_user.admin? && !(user.admin?) && !(user.guest?) %>
              <%= link_to 'このユーザーを削除する', user, method: :delete, data: { confirm: 'このユーザーを削除しますか？' }, class:'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <%= paginate @users %>

  </div>
<% end %>

app/views/users/like.html.erb
<h1 class="text-center mt-4 like-font">Like</h1>
<% if @user.likes.any? %>
  <div id="show-likes">
    <%= render 'users/partial/show_items' %>
  </div>
<% else %>
  <div class="no-contents d-flex justify-content-center align-items-center">
    いいね！ した投稿がありません
  </div>
<% end %>

app/views/users/show.html.erb
<% provide :title, 'マイページ' %>
<h1 class="text-center mt-4 user-font">My Page</h1>
<div class="container mt-5">
  <div class="row mx-auto" style="max-width: 700px;">
    <div class="pr-5 col-md-5">
      <% if @user.avatar? %>
        <%= image_tag(@user.avatar.to_s, size: '250x250', class: 'rounded-circle d-none d-md-inline', alt: 'avatar image') %>
        <%#= image_tag(@user.avatar.to_s, size: '200x200', class: 'rounded-circle d-inline d-md-none', alt: 'avatar image') %>
      <% else %>
        <%= image_tag('no-avatar.png', size: '250x250', class: 'rounded-circle d-none d-md-inline', alt: 'avatar image') %>
        <%#= image_tag('no-avatar.png', size: '200x200', class: 'rounded-circle d-inline d-md-none', alt: 'avatar image') %>
      <% end %>
      <div class="user-name-label font-weight-bold pb-2">
        <%= @user.name %>さん
      </div>
    </div>
    <div class="d-flex flex-column mt-3 col-md-7">
      <div class="user-introduction float-left">
        <%= @user.introduction %>
        <%#= form_with(model: @user, class: "shadow p-3 mb-3 bg-light rounded", local: true) do |f| %>
          <%#= f.text_area :introduction, class: 'form-control', rows: 12, placeholder: '自己紹介を入力してください' %>
<!--          <div class="item-form-btns text-right mb-4">-->
            <%#= f.submit "保存する", class: "btn btn-outline-light btn-lg" %>
<!--          </div>-->
        <%# end %>
      </div>

      <!--      <div class="user-menu pb-2">-->
      <%# if user_signed_in? %>
      <%# if current_user.admin? %>
      <%# if @user.admin? || @user.guest? %>
      <!-- なにも表示しない -->
      <%# else %>
      <%#= link_to 'このユーザーを削除する', @user, method: :delete, data: { confirm: 'このユーザーを削除しますか？' }, class:'btn btn-outline-dark' %>
      <%# end %>
      <%# else %>
      <%# if current_user.id == @user.id %>
      <%#= link_to 'プロフィール編集', edit_user_path(current_user), class:'btn btn-outline-dark' %>
      <%# else %>
      <%#= render 'follow_area', user: @user %>
      <%# end %>
      <%# end %>
      <%# end %>
      <!--      </div>-->
      <!--      <div class="user-profile" style="max-width: 400px; max-height: 140px; overflow: hidden;">-->
      <%#= simple_format(@user.profile) %>
      <!--      </div>-->
    </div>
  </div>


  <ul class="nav nav-tabs justify-content-center mt-3">
    <li class="nav-item">
      <a class="nav-link active" id="items-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true">
        <div class="user-status">
          <span class="status-name">アイテム</span>
          <div class="status-value"><%= @user.items.count.to_s(:delimited) %></div>
        </div>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="coordinates-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="true">
        <div class="user-status">
          <span class="status-name">コーディネート</span>
          <div class="status-value"><%= @user.coordinates.count.to_s(:delimited) %></div>
        </div>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="followings-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="true">
        <div class="user-status">
          <span class="status-name">フォロー</span>
          <div class="status-value" id="followings_<%= @user.id %>">
            <%= @user.followings.count.to_s(:delimited) %>
          </div>
        </div>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="followings-tab" data-toggle="tab" href="#item4" role="tab" aria-controls="item4" aria-selected="true">
        <div class="user-status">
          <span class="status-name">フォロワー</span>
          <div class="status-value" id="followers_<%= @user.id %>">
            <%= @user.followers.count.to_s(:delimited) %>
          </div>
        </div>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="likes-tab" data-toggle="tab" href="#item5" role="tab" aria-controls="item5" aria-selected="true">
        <div class="user-status">
          <span class="status-name">いいね</span>
          <div class="status-value"><%= @user.likes.count.to_s(:delimited) %></div>
        </div>
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade show active" id="item1" role="tabpanel" aria-labelledby="items-tab">
      <% if @user.items.any? %>
        <div id="show-items">
          <div class="flickr_pagination">
            <%= paginate @items %>
          </div>
          <%= render 'items/item', objects: @items %>
          <div class="flickr_pagination">
            <%= paginate @items %>
          </div>
        </div>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          アイテムがありません
        </div>
      <% end %>
    </div>


    <div class="tab-pane fade" id="item2" role="tabpanel" aria-labelledby="coordinates-tab">
      <% if @user.coordinates.any? %>
        <div id="show-coordinates">
          <div class="flickr_pagination">
            <%= paginate @coordinates %>
          </div>
          <%= render 'coordinates/coordinate', objects: @coordinates %>
          <div class="flickr_pagination">
            <%= paginate @coordinates %>
          </div>
        </div>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          コーディネートがありません
        </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="item3" role="tabpanel" aria-labelledby="followings-tab">
      <% if @user.followings.any? %>
        <%= render 'users/partial/follows', objects: @user %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          誰もフォローしていません
        </div>
      <% end %>

    </div>

    <div class="tab-pane fade" id="item4" role="tabpanel" aria-labelledby="followings-tab">
      <% if @user.followers.any? %>
        <%= render 'users/partial/followers', objects: @user %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          フォロワーはいません
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="item5" role="tabpanel" aria-labelledby="likes-tab">
      <% if @user.likes.any? %>
        <div id="show-likes">
          <div class="flickr_pagination">
            <%= paginate @likes %>
          </div>
          <%= render 'users/partial/show_items'%>
          <div class="flickr_pagination">
            <%= paginate @likes %>
          </div>
        </div>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          いいね！ した投稿がありません
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/sign_out.html.erb
<h1>log out</h1>