config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "search_item", to: "items#search"
  get "my_items", to: "items#my_items"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :destroy] do
    resource :friendships, only: [:create, :destroy, :show]
    member do
      get :follows, :followers, :favorites, :items, :like
    end
  end
  resources :coordinates

  get "search_friend", to: "users#search"
  post "save", to: "items#save"
  resources :items do
    collection do
      get "search"
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(9)
  end

  def show
    @items = Item.all.page(params[:page]).per(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index_btn.html.erb
<% if user_signed_in? %>
  <nav class="nav-login nav nav-pills nav-justified navbar-expand-lg mb-2">
    <%= nav_link_add_active('マイページ', user_path(current_user)) %>
    <%= nav_link_add_active('アイテム一覧', items_path) %>
    <%= nav_link_add_active('コーディネート',coordinates_path ) %>
  </nav>
<% else %>
  <nav class="nav-notlogin nav nav-pills nav-justified navbar-expand-lg mb-2">
    <%= nav_link_add_active('アイテム一覧', item_path) %>
    <%= nav_link_add_active('コーディネート',coordinates_path ) %>
  </nav>
<% end %>

app/views/home/_index_item.html.erb
<% if @items.any? %>
  <%= paginate @items %>
  <div class="row item-cards">
    <% @items.each do |item| %>
      <div class="col-lg-4 col-md-12 card-index">
        <div class="card">
          <div class="card-header">
            <div class="item-user">
              <% if item.user.avatar? %>
                <%= link_to image_tag(item.user.avatar.to_s, class: 'user_avatar rounded-circle d-none d-md-inline', alt: 'avatar image'), item.user, class: 'mr-2' %>
              <% else %>
                <%= link_to image_tag('no-avatar.png', class: 'user_avatar rounded-circle d-none d-md-inline', alt: 'avatar image'), item.user, class: 'mr-2' %>
              <% end %>
              <%= link_to item.user.name, item.user %>
            </div>
            <div class="item-info">
              <small><%= item.item_name %></small>
              <br>
              <small><%= item.created_at.to_s(:datetime_jp) %></small>
            </div>
          </div>
          <% if item.image? %>
            <%= link_to image_tag(item.image.to_s, class: 'item_image_index', alt: 'Item image'), items_path %>
          <% else %>
            <%= link_to image_tag('no_image.png', class: 'item_image_index', alt: 'Item image'), items_path %>
          <% end %>

          <div class="card-footer">
            <div>
              <span><%= "いいね！#{item.likes.count}件" %></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @items %>
<% end %>

app/views/home/index.html.erb
<%= render 'index_btn' %>
<%= render 'home/index_item' %>

app/views/home/show.html.erb
<% if @items.any? %>
  <div class="row item-cards">
    <% @items.each do |item| %>
      <div class="col-lg-4 col-md-12 card-index">
        <div class="card">
          <div class="card-header" >
            <div class="item-user">
              <% if item.user.avatar? %>
                <%= link_to image_tag(item.user.avatar.to_s, size: "50x50", class: 'user_avatar rounded-circle d-none d-md-inline', alt: 'avatar image'), item.user, class: 'mr-2' %>
              <% else %>
                <%= link_to image_tag('no-avatar.png',size: "50x50",  class: 'user_avatar rounded-circle d-none d-md-inline', alt: 'avatar image'), item.user, class: 'mr-2' %>
              <% end %>
              <%= link_to item.user.name, item.user %>
            </div>
            <div class="item-info">
<!--              <small><%#= set_address(item.prefecture.name, item.city.name) %></small><br>-->
              <small><%= item.created_at.to_s(:datetime_jp) %></small>
            </div>
          </div>
          <%= link_to image_tag(item.image.to_s, size: "347x350", class: 'item_image_index', alt: 'Item image'), item %>

          <div class="card-footer">
            <div>
<!--              <span><%#= "コメント#{item.comments.count}件" %></span>-->
              <span><%= "いいね！#{item.likes.count}件" %></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>