config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "search_item", to: "items#search"
  get "my_items", to: "items#my_items"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :destroy] do
    resource :friendships, only: [:create, :destroy, :show]
    member do
      get :follows, :followers, :favorites, :items, :like
    end
  end
  resources :coordinates

  get "search_friend", to: "users#search"
  post "save", to: "items#save"
  resources :items do
    collection do
      get "search"
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :coordinates

  has_many :likes, dependent: :destroy
  has_many :likes_items, through: :likes, source: :item

  has_many :active_relationships, class_name:
      "Friendship", foreign_key:
               :following_id, dependent:
               :destroy

  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name:
      "Friendship", foreign_key:
               :follower_id, dependent:
               :destroy
  has_many :followers, through: :passive_relationships, source: :following
  mount_uploader :avatar, ImageUploader


  validates :name, presence: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_save { self.email = email.downcase }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            format: {
                with: VALID_EMAIL_REGEX
            }
  validates :password,
            presence: true,
            length: { minimum: 8 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.search(param)
    param.strip!
    to_send_back = (name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.name_matches(param)
    matches("name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_follows_with?(user)
    !self.followings.where(id: user).exists?
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def update_with_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /coordinates/confirmation/new
  # def new
  #   super
  # end

  # POST /coordinates/confirmation
  # def create
  #   super
  # end

  # GET /coordinates/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, coordinates)
  #   super(resource_name, coordinates)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /coordinates/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /coordinates/password/new
  # def new
  #   super
  # end

  # POST /coordinates/password
  # def create
  #   super
  # end

  # GET /coordinates/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /coordinates/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, if: devise_controller?, only: [:update]
  # before_action :configure_sign_up_params, only: [:update]
  before_action :configure_account_update_params, if: :devise_controller?
  before_action :configure_account_update_params, only: [:update]

  # GET /coordinates/sign_up
  # def new
  #   super
  # end

  # POST /coordinates
  # def create
  #   super
  # end

  # GET /coordinates/edit
  # def edit
  #   super
  # end

  # PUT /coordinates
  def update
    super
  end

  # DELETE /coordinates
  # def destroy
  #   super
  # end

  # GET /coordinates/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, :introduction])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :introduction])
    end

  # The path used after sign up.
  # def after_sign_up_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(coordinates)
  #   super(coordinates)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, if: :devise_controller?




  # GET /coordinates/sign_in
  # def new
  #   super
  # end

  # POST /coordinates/sign_in
  # def create
  #   super
  # end

  # DELETE /coordinates/sign_out
  # def destroy
  #   super
  # end

  protected
    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /coordinates/unlock/new
  # def new
  #   super
  # end

  # POST /coordinates/unlock
  # def create
  #   super
  # end

  # GET /coordinates/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(coordinates)
  #   super(coordinates)
  # end

  # The path used after unlocking the coordinates
  # def after_unlock_path_for(coordinates)
  #   super(coordinates)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :destroy, :follows, :followers]
  before_action :admin_user, only: [:index, :destroy]
  before_action :set_user, only: [:show, :destroy, :followers, :follows]


  def index
    @users = User.order(admin: :DESC, id: :ASC).page(params[:page]).per(5 * 2)
  end


  def show
    @items = @user.items.all.page(params[:page]).per(5)
    @likes = @user.likes.all.page(params[:page]).per(5)
    @coordinates = @user.coordinates.all.page(params[:page]).per(5)
    @friendship = Friendship.new
    @users = @user.followings
  end

  def like
    @user = current_user
    @likes = @user.likes.all.page(params[:page]).per(5)
  end



  def search
    if params[:user].present?
      @users = User.search(params[:user])
      @users = current_user.except_current_user(@users)
      if @users
        respond_to do |format|
          format.js { render partial: "users/partial/friend_result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: "users/partial/friend_result" }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: "users/partial/friend_result" }
      end
    end
  end

  def favorite
    @favorite_items = @user.favorites_items
  end

  def follows
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end



  def destroy
    @user.destroy
    flash[:success] = "ユーザー「#{@user.name}」は正常に削除されました"
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/partial/_followers.html.erb
<div class="row">
  <% @user.followers.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name' %>
        <%= link_to 'Stop Follow', user_friendships_path(user), method: :delete, data: {confirm: 'フォローを解除しますか?'}, class: 'btn btn-sm btn-unfollow'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/partial/_follows.html.erb
<div class="row">
  <% @user.followings.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name' %>
        <%= link_to 'Stop Follow', user_friendships_path(user), method: :delete, data: {confirm: 'フォローを解除しますか?'}, class: 'btn btn-sm btn-unfollow'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/partial/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<%# if !@users.empty? %>
<% if @users.present? %>
  <div class="card  results-block">
    <table class="col-md-12 mt-3 mb-3 ml-5">
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><strong>Name</strong><br><%= user.name%></td>
          <td><strong>Email</strong><br><%= user.email %></td>
          <td><strong>Actions:</strong><br><%= link_to "View Profile", user_path(user), class: "btn btn-sm btn-success btn-user-view" %>
            <% if current_user.not_follows_with?(user) %>
              <%= link_to 'Follow user?', user_friendships_path(user), class: "btn btn-sm btn-primary btn-user-follow", method: :post %>
            <% else %>
              <span class="badge badge-secondar">
              フォローしています
            </span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/partial/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render "/users/partial/friend_result.html" %>'

app/views/users/partial/_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name' %>
        <%= link_to 'Stop Follow', user_friendships_path(user), method: :delete, data: {confirm: 'フォローを解除しますか?'}, class: 'btn btn-sm btn-unfollow'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/partial/_show_items.html.erb
<div class="container">
  <% @user.likes.each do |like| %>
    <div class="row justify-content-md-center">
      <div class="col-lg-8 col-md-12 mt-4">
        <div class="card-text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if like.item.image? %>
              <%#= image_tag like.image.thumb.url %>
              <%= link_to image_tag(like.item.image.to_s, class: "mx-auto d-block item-photo", size: '300x340', alt: 'Item image'), item_path(like.item.id) %>
            <% else %>
              <%= image_tag 'no-image.jpg' %>
            <% end %>
          </div>

          <div class="card-body">
            <h5 class="card-title mb-4"><%= link_to like.item.item_name, item_path(like.user_id), class: "text-success" %></h5>
            <h6 class="card-text">価格　　　　　<%= like.item.price %>円</h6>
            <h6 class="card-text">ブランド　　　<%= like.item.brand %></h6>
            <h6 class="card-text">カテゴリ　　　<%= like.item.category.name %></h6>
            <p class="card-content"><%= like.item.content %></p><br>

            <div class="action-button">
              <% if like.item.user_id == current_user.id %>
                <%= link_to "編集", edit_item_path(like.item.id), class: "btn btn-outline-info" %>
                <%= link_to "削除", item_path(like.item.id), class: "btn btn-outline-danger", id: "delete-button", method: :delete, data: {confirm: "アイテムを削除しますか?"} %>
              <% end %>
            </div>
          </div>
          <div class="card-footer text-muted PhotoBox SlideBox">
            <small>作成日時 <%= like.item.created_at.to_s(:datetime_jp) %>
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
    $(document).on("turbolinks:load", function () {
        $(".PhotoBox").hover(function () {
            $(".SlideBox", this).stop().animate({bottom: "0px"}, "fast");
        }, function () {
            $(".SlideBox", this).stop().animate({bottom: "-70px"}, "slow");
        });
    })
</script>