config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "search_item", to: "items#search"
  get "my_items", to: "items#my_items"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :destroy] do
    resource :friendships, only: [:create, :destroy, :show]
    member do
      get :follows, :followers, :favorites, :items, :like
    end
  end
  resources :coordinates

  get "search_friend", to: "users#search"
  post "save", to: "items#save"
  resources :items do
    collection do
      get "search"
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/views/layouts/_copy.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/layouts/_labels.html.erb
<h1 class="text-center mt-4 first-font">
  <% if params['controller'] == 'users/registrations' %>
  Sign Up
  <% else %>
    Log in
  <% end %>
</h1>

  <div class="text-center mb-4">
  <p>自分の好きな洋服から繋がるアプリです。気に入ったアイテムでコーディネートを組んでシェアしましょう</a>
  </p>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      <%= alert %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-xl navbar-dark sticky-top">
  <%#= link_to image_tag('Wearing-Connect', class: 'navbar-logo'), root_path, class: 'navbar-brand' %>
  <%= link_to('Wearing Connect', root_path, class: 'navbar-brand first-font') %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? && current_user.admin?  %>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'users') + ' すべてのユーザー', users_path) %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'rss') + 'アイテム一覧', items_path) %>
        </li>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'search') + ' アイテム検索', my_items_path) %>
        </li>
        <li class="nav-item">
          <%= header_link_item(icon('fa', 'user-plus') + '友達', follows_user_path(current_user.id)) %>
        </li>

      <li class="nav-item">
        <%= header_link_item(icon('fa', 'heart') + 'お気に入り', like_user_path(current_user.id)) %>
      </li>
      <li class="nav-item dropdown">
        <%= link_to icon('fas', 'tshirt') + 'コーディネート', '#', class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }  %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to icon('fas', 'edit') + '作成', new_coordinate_path, class: 'dropdown-item' %>
          <%= link_to icon('fas', 'rss') + '一覧', coordinates_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'edit') + ' 新しいアイテム', new_item_path) %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to icon('fas', 'user') + " #{current_user.name}さん", '#', class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to icon('fas', 'user') + ' マイページ', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to icon('fas', 'sign-out-alt') + ' ログアウト', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: {confirm: "ログアウトしますか？"} %>
            <%= link_to icon('fas', 'edit') + '編集', edit_user_registration_path, class: 'dropdown-item', data: {confirm: 'ユーザー情報を編集しますか？'} %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'user-plus') + ' 新規登録', new_user_registration_path) %>
        </li>
        <li class="nav-item">
          <%= header_link_item(icon('fas', 'sign-in-alt') + ' ログイン', new_user_session_path) %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WearingConnect</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
<%= render 'layouts/navigation' %>
<div class="container">
<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
      <%= msg.html_safe %>
    </div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>